MAIN_LOGGER_NAME = 'main'
OPENAI_LOGGER_NAME = 'openai'
FEED_LOGGER_NAME = 'feed'
SUMMARY_LOGGER_NAME = 'summary'
LOGGERS = [
    MAIN_LOGGER_NAME, OPENAI_LOGGER_NAME, FEED_LOGGER_NAME, SUMMARY_LOGGER_NAME
]
PINECONE_KEY = "#KEY"